services:
  datadog-agent:
    image: registry.datadoghq.com/agent:7
    container_name: dd-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_ENV=${DD_ENV}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

  postgres:
    image: postgres:18.4
    mem_limit: 512m
    cpus: 1.0
    hostname: postgres
    container_name: terminal-request-service-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: terminal_request_service
      POSTGRES_PASSWORD: terminal_request_service
      POSTGRES_DB: terminal_request_service
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:3.8
    container_name: localstack_main
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=0
      - LS_LOG=error
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./docker/localstack/init:/etc/localstack/init/ready.d"
      - "./docker/localstack/lambdas:/tmp/lambdas"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres_data:
    name: terminal_request_service_postgres_volume
