services:
  app:
    image: terminal-request-service:latest
    entrypoint: [
      "sh",
      "-c",
      "java $${JAVA_OPTS} -javaagent:/app/dd-java-agent.jar -Ddd.service=$${DD_SERVICE} -Ddd.env=$${DD_ENV} -Ddd.version=$${DD_VERSION} -cp \"/app/application/*:/app/lib/*\" com.desafio.terminalrequest.TerminalRequestApplication"
    ]
    mem_limit: 1024m
    cpus: 0.5
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - datadog-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=terminal-request-service
      - DD_ENV=${DD_ENV}
      - DD_VERSION=${DD_VERSION}
      - DD_LOGS_INJECTION=true
      - DD_PROFILING_ENABLED=true
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/terminal_request_service
      - POSTGRES_USERNAME=terminal_request_service
      - POSTGRES_PASSWORD=terminal_request_service
      - AWS_REGION=us-east-1
      - AWS_LAMBDA_ENABLED=true
      - AWS_LAMBDA_CUSTOMER_VALIDATION_FUNCTION=http://localstack:4566/2015-03-31/functions/customer-validation/invocations
      - AWS_LAMBDA_TERMINAL_RESERVATION_FUNCTION=http://localstack:4566/2015-03-31/functions/terminal-reservation/invocations
      - AWS_LAMBDA_TERMINAL_RESERVATION_COMPENSATOR_FUNCTION=http://localstack:4566/2015-03-31/functions/terminal-reservation-compensator/invocations
      - AWS_LAMBDA_DELIVERY_FUNCTION=http://localstack:4566/2015-03-31/functions/delivery-scheduling/invocations

  datadog-agent:
    image: registry.datadoghq.com/agent:7
    container_name: dd-agent
    mem_limit: 512m
    cpus: 0.5
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_ENV=${DD_ENV}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  postgres:
    image: postgres:18.4
    mem_limit: 2048m
    cpus: 1.0
    hostname: postgres
    container_name: terminal-request-service-postgres
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: terminal_request_service
        POSTGRES_PASSWORD: terminal_request_service
        POSTGRES_DB: terminal_request_service
        PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:3.8
    container_name: localstack_main
    mem_limit: 1024m
    cpus: 0.5
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=0
      - LS_LOG=error
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./docker/localstack/init:/etc/localstack/init/ready.d"
      - "./docker/localstack/lambdas:/tmp/lambdas"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres_data:
    name: terminal_request_service_postgres_volume
